apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: flags-api
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: flags-quiz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # Uncomment and set storageClassName if needed
  # storageClassName: standard
