apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: flags-api
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: flags-quiz
spec:
  type: ClusterIP
  ports:
    - port: 53306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: flags-api
  labels:
    app.kubernetes.io/name: php
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: flags-quiz
spec:
  type: ClusterIP
  ports:
    - port: 59000
      targetPort: 9000
      protocol: TCP
      name: php-fpm
  selector:
    app.kubernetes.io/name: php
---
apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: flags-api
  labels:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: flags-quiz
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31180
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: caddy
