services:
    php:
        environment:
            VERSION_HASH: "${GITHUB_SHA:-none}"
            SYMFONY_DECRYPTION_SECRET: "${SYMFONY_DECRYPTION_SECRET}"
            APP_ENV : "prod"
        extends:
            file: docker-compose.yml
            service: php
        image: ${IMAGE}:php-latest
        build:
            dockerfile: .docker/php-fpm/Dockerfile
        networks:
            - backend-flags
    nginx:
        extends:
            file: docker-compose.yml
            service: nginx
        image: ${IMAGE}:nginx-latest
        container_name: "nginx-${PROJECT_NAME}"
        ports:
            - "8080:80"
            - "4443:443"
        networks:
            - backend-flags
    db:
        extends:
            file: docker-compose.yml
            service: db
        image: ${IMAGE}:db-latest
        ports:
            - "33060:3306"
        networks:
            - backend-flags
networks:
    backend-flags:
        external: true
volumes:
    db-data-flags: ~
