services:
    php:
        build:
          args:
            USER_ID: 1000
            GROUP_ID: 1000
          target: development
        volumes:
            - .:/var/www/html:rw,cached
    db:
        ports:
            - "3306:3306"
    caddy:
        ports:
            - "8000:80"
            - "4430:443"
        volumes:
            - ./:/var/www/html:cached
            - caddy_data:/data
            - caddy_config:/config
            - caddy_logs:/var/log/caddy
        build:
          dockerfile: .docker/caddy/Dockerfile